name: Update WAB data

on:
  schedule:
    - cron: '5 */4 * * *' # Runs on the fifth minute of every sixth hour

jobs:
  update:
    runs-on: macos-latest
    env:
      CBD_USER: ${{ secrets.CBD_USER }}
      CBD_PW: ${{ secrets.CBD_PW }}
      GITHUB_PAT: ${{ secrets.GIT_PAT }}
    strategy:
      matrix:
        r-version: [4.2.0]

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages(c("dplyr", "rvest", "readr", "glue", "purrr", "janitor", "remotes"))
          remotes::install_github("andreweatherman/cbbdata")
        shell: Rscript {0}
      - name: Update WAB Data
        run: Rscript -e 'source("fetch_data.R")'
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git pull
          git add .
          git commit -m "[Automate] update WAB data" || "no changes to commit"
          git push || echo "No changes to commit"